### ISSUE TITLE
退出时报错

### ISSUE THREAD

**Issue by hhrensheng** [newfyu/OpenCopilot#4]
`Uncaught Exception:
TypeError: Object has been destroyed
at ChildProcess.<anonymous> (/Applications/OpenCopilot.app/Contents/Resources/app.asar/index.js:1:5542)
at ChildProcess.emit (events.js:315:20)
at maybeClose (internal/child_process.js:1048:16)
at Socket.<anonymous> (internal/child_process.js:439:11)
at Socket.emit (events.js:315:20)
at Pipe.<anonymous> (net.js:673:12)`
mac 右键退出会报js错误

**Comment by hhrensheng** [comment]
![image](https://github.com/newfyu/OpenCopilot/assets/29398035/2a0a3590-b614-4c47-becd-4e654939a829)

**Comment by newfyu** [comment]
退出有时候报错问题修复了，近期更新下

**Comment by newfyu** [comment]
0.4上传了，可以试一下还有这个问题没

**Comment by hhrensheng** [comment]
> 0.4上传了，可以试一下还有这个问题没

好的，谢谢
